# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Spatial Analytics Portfolio"
description: "Powered by Jekyll and GitHub Pages"
author:      "Anna Duan"

collections:
  projects:
    output: true
    permalink: /:collection/:title
    # sort_by: date
    # sort_reverse: true